import moduleResolver from "./moduleResolver.ts";

// Map of `from=>to[,from2=>to2]` prefixes, read from the environment. It rewrites
// the absolute paths baked into the generated declarations so go-to-definition
// lands on files where the editor actually runs. This matters when the build
// runs in a container but the editor opens the same files at a different mount
// (e.g. theme sources served at /var/www/html in the container but edited at the
// host bind-mount). An empty map is the identity — correct when the build and
// editor share a filesystem.
function parsePathMap(raw?: string): Array<[string, string]> {
    if (!raw) return [];
    return raw
        .split(",")
        .map((pair) => pair.split("=>").map((part) => part.trim()))
        .filter(
            (parts): parts is [string, string] => parts.length === 2 && !!parts[0] && !!parts[1],
        )
        .map(([from, to]) => [from, to]);
}

function remapPath(filePath: string, map: Array<[string, string]>): string {
    for (const [from, to] of map) {
        if (filePath.startsWith(from)) return to + filePath.slice(from.length);
    }
    return filePath;
}

function declaration(specifier: string, target: string, isVue: boolean): string {
    // SFCs always default-export the component; other modules (stores, libs) can
    // expose named exports, so re-export the namespace for those.
    const body = isVue
        ? `    export { default } from ${JSON.stringify(target)};`
        : `    export * from ${JSON.stringify(target)};`;
    return `declare module ${JSON.stringify(specifier)} {\n${body}\n}`;
}

/**
 * Generate a `.d.ts` declaring the framework's `Vendor_Module::` import
 * specifiers for a theme, re-exporting each from the real source file so editors
 * give autocomplete and go-to-definition on explicit imports. Built from the
 * same inheritance cache the resolver uses, so the declared set matches exactly
 * what the build will resolve (only `.js`/`.vue` — assets are not in the cache).
 */
export default async function generateComponentTypes(themeName: string): Promise<string> {
    const files = (await moduleResolver.getAllJsVueFilesWithInheritance(themeName)) as Record<
        string,
        string
    >;
    const map = parsePathMap(process.env.MAGE_OBSIDIAN_TYPES_PATH_MAP);

    const blocks: string[] = [];
    for (const [key, absolutePath] of Object.entries(files)) {
        const slash = key.indexOf("/");
        if (slash === -1) continue;
        const namespace = key.slice(0, slash);
        const rest = key.slice(slash + 1);
        const target = remapPath(absolutePath, map);
        const isVue = absolutePath.endsWith(".vue");

        blocks.push(declaration(`${namespace}::${rest}`, target, isVue));
        if (rest.startsWith("components/")) {
            // The resolver accepts the shorthand without the `components/` prefix.
            blocks.push(
                declaration(`${namespace}::${rest.slice("components/".length)}`, target, isVue),
            );
        }
    }

    const header =
        "// Generated by mage-obsidian. Declares the framework's `Vendor_Module::`\n" +
        "// import specifiers for editor autocomplete and go-to-definition.\n" +
        "// Regenerated on every build — do not edit.\n\n";

    return `${header}${blocks.join("\n\n")}\n`;
}
