import path from "node:path";
import moduleResolver from "./moduleResolver.ts";

// Map of `from=>to[,from2=>to2]` prefixes, read from the environment. It rewrites
// the absolute paths baked into the generated jsconfig so go-to-definition and
// npm resolution land on files where the editor actually runs. This matters when
// the build runs in a container but the editor opens the same files at a
// different mount (e.g. theme sources served at /var/www/html in the container
// but edited at the host bind-mount). An empty map is the identity — correct
// when the build and editor share a filesystem.
function parsePathMap(raw?: string): Array<[string, string]> {
    if (!raw) return [];
    return (
        raw
            .split(",")
            .map((pair) => pair.split("=>").map((part) => part.trim()))
            .filter(
                (parts): parts is [string, string] =>
                    parts.length === 2 && !!parts[0] && !!parts[1],
            )
            .map(([from, to]) => [from, to] as [string, string])
            // Longest `from` first so a more specific mount (e.g. the vite harness
            // overlaid at /var/www/html/vite) wins over a broader one
            // (/var/www/html) regardless of declaration order.
            .sort((a, b) => b[0].length - a[0].length)
    );
}

function remapPath(filePath: string, map: Array<[string, string]>): string {
    for (const [from, to] of map) {
        if (filePath.startsWith(from)) return to + filePath.slice(from.length);
    }
    return filePath;
}

// The Vite harness install (the `vite/` dir is the cwd during a build) is where
// the build resolves bare npm specifiers, so point the editor at the same place.
// Wildcard so `vue`, `@heroicons/vue/...`, `pinia` and friends all resolve.
function nodeModulesWildcard(map: Array<[string, string]>): string {
    return path.join(remapPath(path.resolve(process.cwd(), "node_modules"), map), "*");
}

/**
 * Build the `compilerOptions.paths` map that makes the framework's
 * `Vendor_Module::` import specifiers first-class for the editor: each maps
 * directly to its real source file, so Ctrl+click jumps straight there and a
 * typo surfaces as an unresolved import. Derived from the same inheritance cache
 * the resolver uses, so the declared set matches exactly what the build resolves
 * (only `.js`/`.vue` — assets are not in the cache). A `"*"` wildcard adds npm
 * package resolution from the harness node_modules.
 */
export default async function generateJsconfigPaths(
    themeName: string,
): Promise<Record<string, string[]>> {
    const files = (await moduleResolver.getAllJsVueFilesWithInheritance(themeName)) as Record<
        string,
        string
    >;
    const map = parsePathMap(process.env.MAGE_OBSIDIAN_TYPES_PATH_MAP);

    const paths: Record<string, string[]> = {
        "*": [nodeModulesWildcard(map)],
    };

    for (const [key, absolutePath] of Object.entries(files)) {
        const slash = key.indexOf("/");
        if (slash === -1) continue;
        const namespace = key.slice(0, slash);
        const rest = key.slice(slash + 1);
        const target = remapPath(absolutePath, map);

        paths[`${namespace}::${rest}`] = [target];
        if (rest.startsWith("components/")) {
            // The resolver accepts the shorthand without the `components/` prefix.
            paths[`${namespace}::${rest.slice("components/".length)}`] = [target];
        }
    }

    return paths;
}

const GENERATED_MARKER = "// Generated by mage-obsidian";

/**
 * Wrap a `paths` map in the full theme jsconfig the editor consumes. `allowJs`
 * is required or the theme's `.js`/`.vue` sources never join the TS program (so
 * nothing resolves); `baseUrl` is deliberately omitted — it is deprecated and a
 * hard config error in TS 7.0, which makes the editor discard the whole config.
 * The leading marker comment lets the build tell its own output apart from a
 * hand-written jsconfig and refuse to clobber the latter.
 */
function buildThemeJsconfig(paths: Record<string, string[]>): string {
    const jsconfig = {
        compilerOptions: {
            allowJs: true,
            checkJs: false,
            module: "esnext",
            moduleResolution: "bundler",
            paths,
        },
        include: ["**/*.js", "**/*.vue"],
        exclude: ["**/generated/**", "node_modules"],
    };
    const header = `${GENERATED_MARKER} — do not edit. Refreshed on every build and live in dev.\n`;
    return `${header}${JSON.stringify(jsconfig, null, 4)}\n`;
}

export { buildThemeJsconfig, GENERATED_MARKER };
