import path from "path";
import fs from "fs/promises";
import moduleResolver from "./moduleResolver.ts";
import {
    PRECOMPILED_FOLDER,
    ALL_JS_VUE_FILES_WITH_INHERITANCE_FILE_NAME,
} from "../config/default.ts";
import getCssImports from "./cssResolver.ts";
import configResolver from "./configResolver.ts";
import generateJsconfigPaths, { buildThemeJsconfig, GENERATED_MARKER } from "./generateJsconfig.ts";
import { fileURLToPath } from "url";
const __filename = fileURLToPath(import.meta.url);
const __dirname = path.dirname(__filename);

async function writeToFile(outputPath, content) {
    await fs.mkdir(path.dirname(outputPath), { recursive: true });
    await fs.writeFile(outputPath, content, "utf-8");
}

async function precompileCss(themeName) {
    const cssContent = await getCssImports(themeName);
    const outputPath = path.resolve(PRECOMPILED_FOLDER, themeName, "precompiled.css");
    await writeToFile(outputPath, cssContent);
}

async function precompileJs(themeName) {
    const baseJsPath = path.resolve(__dirname, "../templates/base_main_js_file.js");
    const jsOutputPath = path.resolve(PRECOMPILED_FOLDER, themeName, "precompiled.js");
    await fs.copyFile(baseJsPath, jsOutputPath);

    const vueFilesOutputPath = path.join(
        PRECOMPILED_FOLDER,
        themeName,
        ALL_JS_VUE_FILES_WITH_INHERITANCE_FILE_NAME,
    );
    const vueFiles = await moduleResolver.getAllJsVueFilesWithInheritance(themeName);
    await writeToFile(vueFilesOutputPath, JSON.stringify(vueFiles));
}

// Write the theme's jsconfig.json (gitignored) so the author's editor — which
// opens the theme sources directly — resolves the framework's `Vendor_Module::`
// specifiers and npm packages via `paths`. Refuses to clobber a hand-written
// jsconfig: only (re)writes one carrying our generated marker, or creates one
// when absent. Skipped silently if the theme has no src.
async function precompileJsconfig(themeName) {
    const themeDefinition = configResolver.getThemeDefinition(themeName);
    if (!themeDefinition?.src) return;
    const outputPath = path.join(themeDefinition.src, "jsconfig.json");

    let existing;
    try {
        existing = await fs.readFile(outputPath, "utf-8");
    } catch {
        existing = null;
    }
    if (existing !== null && !existing.startsWith(GENERATED_MARKER)) {
        console.warn(
            `[mage-obsidian] ${outputPath} is not generated by mage-obsidian; leaving it untouched. ` +
                "Remove it to let the build manage Vendor_Module:: import resolution.",
        );
        return;
    }

    const paths = await generateJsconfigPaths(themeName);
    const content = buildThemeJsconfig(paths);
    if (existing === content) return;
    await writeToFile(outputPath, content);
}

export { precompileCss, precompileJs, precompileJsconfig };
