import { vi } from "vitest";
import path from "node:path";

const MARKER = "// Generated by mage-obsidian";
const THEME_SRC = "/var/www/html/app/design/frontend/Vendor/theme";
const OUTPUT = path.join(THEME_SRC, "jsconfig.json");
const CONTENT = `${MARKER}\n{"compilerOptions":{}}\n`;
const TS_OUTPUT = path.join(THEME_SRC, "tsconfig.typecheck.json");
const TS_CONTENT = `${MARKER}\n{"compilerOptions":{"noEmit":true}}\n`;

function setup({ existing } = {}) {
    const readFile = vi.fn(async () => {
        if (existing === undefined) {
            const error = new Error("ENOENT");
            throw error;
        }
        return existing;
    });
    const writeFile = vi.fn(async () => {});
    const mkdir = vi.fn(async () => {});
    const warn = vi.spyOn(console, "warn").mockImplementation(() => {});

    vi.doMock("fs/promises", () => ({ default: { readFile, writeFile, mkdir } }));
    vi.doMock("../../core/moduleResolver.ts", () => ({ default: {} }));
    vi.doMock("../../core/cssResolver.ts", () => ({ default: vi.fn() }));
    vi.doMock("../../core/configResolver.ts", () => ({
        default: { getThemeDefinition: () => ({ src: THEME_SRC }) },
    }));
    vi.doMock("../../core/generateJsconfig.ts", () => ({
        default: vi.fn(async () => ({ "Theme::Foo": ["/abs/Foo.vue"] })),
        buildThemeJsconfig: () => CONTENT,
        buildThemeTsconfig: () => TS_CONTENT,
        GENERATED_MARKER: MARKER,
    }));

    return { readFile, writeFile, warn };
}

async function run() {
    const { precompileJsconfig } = await import("../../core/preCompileFiles.ts");
    await precompileJsconfig("Vendor/theme");
}

async function runTs() {
    const { precompileTsconfig } = await import("../../core/preCompileFiles.ts");
    await precompileTsconfig("Vendor/theme");
}

describe("precompileJsconfig", () => {
    beforeEach(() => {
        vi.resetModules();
        vi.clearAllMocks();
    });

    afterEach(() => {
        vi.restoreAllMocks();
    });

    test("creates the jsconfig when none exists", async () => {
        const { writeFile } = setup({ existing: undefined });
        await run();
        expect(writeFile).toHaveBeenCalledWith(OUTPUT, CONTENT, "utf-8");
    });

    test("refuses to clobber a hand-written (unmarked) jsconfig", async () => {
        const { writeFile, warn } = setup({ existing: `{"compilerOptions":{"baseUrl":"."}}` });
        await run();
        expect(writeFile).not.toHaveBeenCalled();
        expect(warn).toHaveBeenCalled();
    });

    test("skips the write when the generated content is unchanged", async () => {
        const { writeFile } = setup({ existing: CONTENT });
        await run();
        expect(writeFile).not.toHaveBeenCalled();
    });

    test("rewrites a marked jsconfig whose content drifted", async () => {
        const { writeFile } = setup({ existing: `${MARKER}\n{"stale":true}\n` });
        await run();
        expect(writeFile).toHaveBeenCalledWith(OUTPUT, CONTENT, "utf-8");
    });
});

describe("precompileTsconfig", () => {
    beforeEach(() => {
        vi.resetModules();
        vi.clearAllMocks();
    });

    afterEach(() => {
        vi.restoreAllMocks();
    });

    test("writes the gate tsconfig to tsconfig.typecheck.json (not tsconfig.json)", async () => {
        const { writeFile } = setup({ existing: undefined });
        await runTs();
        expect(writeFile).toHaveBeenCalledWith(TS_OUTPUT, TS_CONTENT, "utf-8");
    });

    test("refuses to clobber a hand-written (unmarked) tsconfig", async () => {
        const { writeFile, warn } = setup({ existing: `{"compilerOptions":{"strict":true}}` });
        await runTs();
        expect(writeFile).not.toHaveBeenCalled();
        expect(warn).toHaveBeenCalled();
    });

    test("skips the write when the generated content is unchanged", async () => {
        const { writeFile } = setup({ existing: TS_CONTENT });
        await runTs();
        expect(writeFile).not.toHaveBeenCalled();
    });
});
